apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  POSTGRES_PASSWORD: "1234"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
  JWT_SECRET: "changeme"
  GRAFANA_PASSWORD: "admin"
  DATABASE_URL_AUTH: "postgresql+psycopg2://admin:1234@auth-db:5432/db_auth"
  DATABASE_URL_MGMT: "postgresql+psycopg2://admin:1234@mgmt-db:5432/db_devices"
