global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8001"]

  - job_name: "management-service"
    static_configs:
      - targets: ["device-management:8002"]

  - job_name: "monitoring-service"
    static_configs:
      - targets: ["device-monitoring:8003"]
